### ISSUE TITLE
Encoder Attribution

### ISSUE THREAD

**Issue by ghost** [AnimeThemes/animethemes-server#178]
At the very least, we should have something like the "Volunteer encoders" list on openings.moe/hub.

Perhaps we should allow for attribution on each video, which would allow us to do things like aggregate counts for leaderboards and such.

For registered users there should be team membership.

**Comment by paranarimasu** [comment]
In relation to #223, we can perhaps designate members of this team as a circle of trust of encoders. I.e, certain roles granted in this team allow the encoder to bypass restrictions for limiting outstanding submissions or the global feature flag to shut down new submissions.
