### ISSUE TITLE
api/search returns invalid video link

### ISSUE THREAD

**Issue by irevenko** [AnimeThemes/animethemes-server#195]
Resource: https://staging.animethemes.moe/api/search?q=&limit=1&fields[search]=anime&include=themes.entries.videos%2Cthemes.song.artists%2Cimages

Returns broken link
`"link": "https://staging.animethemes.moe/video/BlendS-OP1-BD1080.webm"`

But in docs: https://staging.animethemes.moe/api/docs 
the link doesn't have `staging` prefix
![image](https://user-images.githubusercontent.com/44785096/117809035-7eb6d980-b212-11eb-8493-2ea303da706b.png)

**Comment by paranarimasu** [comment]
Hello, per #44 we will be removing code-generated docs in favor of an external project to manage them. At the moment, these docs are not being maintained and may be outdated. This effort will begin in the near future.

The `link` attribute of the video api resource uses the URL generator of the framework and the named route for video streams to create this link. The URL generator uses the application url which is configured in the `.env` file.

That is to say, in the staging environment, you get links to videos in the staging environment. In the production environment, you will get links to videos in the production environment.

In the staging environment, video streaming is disabled. You'll get redirected to the home screen, as is designed.

Personally, I am not in favor of generating links strictly to the production environment, be it this particular link or any others in the application. This does mean that string manipulation is needed for anyone using the API as it exists now in this environment; I know that there are a few projects leverages our API that have to do this now.

Please keep in mind that this environment targets our development efforts. If you are making use of our API at this time before we have officially released it to our production environments, you will encounter inconveniences such as this.

For now, I don't think there's anything actionable in this issue, so I will be closing it.
