### ISSUE TITLE
Links to streaming

### ISSUE THREAD

**Issue by ghost** [AnimeThemes/animethemes-server#233]
Note: WIP. Discussion is encouraged. This does not target our wiki deployment and will instead be its own project.

## Goals

Allow users to discover legal streaming links for anime

## User Stories

A user shall be able to discover links to legal streaming when browsing themes.

A user shall be able to query for links to legal streaming in the API.

## Functional requirements

(Needs research, will revisit)

**Comment by paranarimasu** [comment]
Idea: Support links to both music streaming services like spotify and anime streaming services like crunchyroll.

**Comment by along517** [comment]
Sites such as [Kitsu](https://kitsu.io/) and [LiveChart](https://www.livechart.me/) also have this function of showing legal streaming sites. [AniPlaylist](https://aniplaylist.com/) also has links to music streaming services. This might be helpful on how to do it or if the function is needed.

**Comment by along02** [comment]
MAL now shows streaming sites now as well. https://myanimelist.net/forum/?topicid=1990845 Maybe that will help.

**Comment by Kyrch** [comment]
* Added Song-Resource Pivot (#602)
* Added new resource sites as Spotify, YouTube Music, YouTube, Apple Music & Amazon Music (#603)
