### ISSUE TITLE
Fuzzy search for themes/shows

### ISSUE THREAD

**Issue by JoseiToAoiTori** [AnimeThemes/animethemes-server#29]
The current endpoints require the exact alias or theme ID to work which is good for retrieving data for a specific show/theme but not for searching purposes. Some POST end-points that take a search variable and perform fuzzy search on the database to return an array of matches would be nice.

A good Fuzzy Search solution I use in JavaScript is Fuse.js. It has a PHP equivalent [here](https://github.com/loilo/Fuse).

**Comment by paranarimasu** [comment]
**Housekeeping:** As of now this is implemented on the release branch.

`/api/search?q=XXXX...`
