### ISSUE TITLE
Endpoint for retrieving themes from a particular year

### ISSUE THREAD

**Issue by JoseiToAoiTori** [AnimeThemes/animethemes-server#30]
I'm not sure how much use this end-point might have overall but one of my use-cases of the AnimeThemes database is to scrape all themes from a single year and create a database of them. I do this for the /r/anime Awards to build a database for OP/ED voting but if there were an endpoint for it instead, it would make things a lot easier as our scraping doesn't include data such as artist and also can't grab higher quality versions of themes. The response might have to be paginated for the large volume of data returned too.

**Comment by paranarimasu** [comment]
**Housekeeping:** As of now this is implemented on the release branch.

`/api/anime?filter[year]=####...`
