### ISSUE TITLE
Configure Pivot API Endpoints

### ISSUE THREAD

**Issue by ghost** [AnimeThemes/animethemes-server#368]
We should have API endpoints for each pivot class like we do for each public-facing model. The existing API framework should accommodate these classes fairly easily.

**Comment by paranarimasu** [comment]
Note: The ambiguity of pivot information in related resources is an issue for animethemes-web typing, so as these are implemented, we should explore including pivot resources as allowed includes rather than the contentional way of conditionally including pivot information on the related resource.
