### ISSUE TITLE
a way to get all OPs and EDs from a certain anime

### ISSUE THREAD

**Issue by nomis6432** [AnimeThemes/animethemes-server#4]
I want to make a small linux script that will download/update all anime OPs/EDs from the anime I've seen but it looks like the site currently only offers a list of all available OPs/EDs but no way to search them and the names used are not consistent with the names on MAL.

I don't know what your database looks like but do you keep the MAL ID of the shows? If so could it be possible to get all OPs/EDs from a show by for instance going to animethems.moe/malid/$MALID .

I've never used laravel and don't know much about PHP but I can take a look at it. An api would also be a good solution but I also don't have a lot of experience with this but I don't think it should be that hard since it doesn't require any form of authentication.

I'd also like to thank you for maintaining this project and all the folks on reddit for making this all possible. I'm glad I don't have to look on youtube anymore in the hope of finding the OP/ED I want to listen to.

**Comment by TFSThiagoBR98** [comment]
For better database normalization, we have to create an Anime Table, a Theme Table, a Mapping Table (Store Ids from Mal, Anilist, Kitsu, etc.) and the Video Table

**Comment by nomis6432** [comment]
You're right. I just wrote this on the spot and didn't really think it through since I don't have much time now. I don't think we have to follow 3NF completely since that may make some SQL queries slower. I'll try to model an example database tomorrow.

**Comment by nomis6432** [comment]
![animethemes](https://user-images.githubusercontent.com/18666125/45100535-f19a5900-b129-11e8-9482-de02ed565db4.png)
Here is a suggestion for the database. I made this with MySQL Workbench and [here](http://nomis.ulyssis.be/files/animethemes.mwb) is the model. Feel free to suggest any improvements. 

I believe we should be able to extract the information we need from the wiki (with a markdown parser, [flexmark](https://github.com/vsch/flexmark-java) for example) an the anilist API (since I believe the mal API is still down)

**Comment by paranarimasu** [comment]
Apologies for the silence on my end. I'd just like to address the scope of the discussion since the initial comment makes mention of an API as well. I'll take some time this weekend to compartmentalize everything into projects and tasks. I will be sure to provide feedback then. For now, I'm okay with leaving this ticket for discussion of the database schema. Feel free to continue with that discussion.

**Comment by TFSThiagoBR98** [comment]
I think we can:

- Add a column artist in animethemes;
- Add a column notes  in animethemes;
- Add a column episodes in animethemes;
- Add a column hascredits in videos;
- Add a column source in videos;

**Comment by nomis6432** [comment]
I've added your suggestions:
![animethemesv2](https://user-images.githubusercontent.com/18666125/45120124-89fe0100-b15d-11e8-8c87-0c6d55c7e282.png)
the updated MySQL Workbench model can be found [here](http://nomis.ulyssis.be/files/animethemesV2.mwb)

[Here](https://gitlab.com/TFSThiagoBR98/Antx) is @TFSThiagoBR98 's animethemes parser. This might be useful to extract the data from the wiki.

**Comment by TFSThiagoBR98** [comment]
Put has_credits and source columns in video table because they are applied per video, otherwise the rest is fine.

**Comment by nomis6432** [comment]
Fixed it:
![animethemesv2](https://user-images.githubusercontent.com/18666125/45155174-62994980-b1da-11e8-8f00-f8ea7fbbadc6.png)
I've also changed animenames.language to CHAR(3) instead of VARCHAR(3) since all languages can be resembled by 3 characters.
[MySQL model](http://nomis.ulyssis.be/files/animethemesV2.mwb) is also updated.
