### ISSUE TITLE
Featured Theme Model

### ISSUE THREAD

**Issue by ghost** [AnimeThemes/animethemes-server#470]
Currently we provide the featured theme through a pair of settings that override application config defaults. While this does allow mods the ability to manage the featured theme in-system, this still requires external maintenance through a spreadsheet to represent scheduled changes. Mods also to make timely changes to adhere to the schedule.

Instead, we should be able to populate this schedule in-system through a `FeaturedTheme` Admin model.

Proposed Structure:

* featured_theme_id (pk)
* entry_id (foreign constrained)
* video_id (foreign constrainted)
* start_at (timestamp)
* end_at (timestamp)

Other requirements:

* API Resource
* Nova Resource
* Prune old feature theme settings
* Update API Documentation

Optional Suggestions:

Ability to attribute the featured theme to a user that suggested it?

**Comment by paranarimasu** [comment]
Suggestion: We might want to consider limiting the visibility to featured themes that are planned for future weeks.

For example, a `GET /featuredtheme/` index endpoint might only return featured themes whose start date is on or before the current date.

Similarly, a `GET /featuredtheme/{id}` show endpoint might forbid the viewing of a featured theme whose start date is after the current date.

For simplicity, we might want a separate endpoint to retrieve the current featured theme. IMO the `/config/wiki` endpoint isn't expressive. Something like `featuredtheme/current` makes more sense.
