### ISSUE TITLE
Grant Default Permissions to new users on registration

### ISSUE THREAD

**Issue by ghost** [AnimeThemes/animethemes-server#488]
We want to assign new users a set of permissions to grant the ability to perform basic actions like managing playlists. This gives us the ability to soft-ban users at moderator's discretion.

We might need to manage whether permissions are granted by default in the database.

A proposal for default permissions:

* [x] create/update/delete/restore playlist
* [x] create/update/delete/restore playlist track

**Comment by paranarimasu** [comment]
Added granting default roles to newly verified users in #508. Deployed to beta. Needs verification in animethemes-web auth scaffolding.
