### ISSUE TITLE
Add Media Type / Format Attribute to Anime

### ISSUE THREAD

**Issue by ghost** [AnimeThemes/animethemes-server#583]
MAL/Anilist/AniDB/Kitsu classify anime entries by type/format.

For example, Bakemonogatari is listed as media type / format `TV`:

https://myanimelist.net/anime/5081/
https://anilist.co/anime/5081/
https://anidb.net/anime/6327
https://kitsu.io/anime/bakemonogatari
https://www.anime-planet.com/anime/bakemonogatari

There are some edge cases where two or more anime have the same title but different formats / media types. This information might also be useful for distinguishing / filtering anime.

From internal discussions, we agree with the guidelines on MAL for classifying anime by media type, so we can seed these values using their API and backfill any gaps manually.

* [x] Create new MediaType or MediaFormat enum to represent this attribute
* [x] Register new attribute in model, including casting
* [x] Create Migration to add new attribute on Anime model
* [x] Define new field in API resource
* [x] Update API docs
* [x] Add new field in Nova resource
* [x] Create database seeder that utilizes MAL API. This can be pruned after deployment and verification. I do not believe we need to maintain an action class for this. We can require this field to be filled by wiki editors in the future.
* [x] Modify Elasticsearch migration to include new field in index documents

**Comment by Kyrch** [comment]
Deployed in beta, waiting beta release to seed in main production
