### ISSUE TITLE
Using a Comparison Operator on Filtering returns an error

### ISSUE THREAD

**Issue by ferrazza11** [AnimeThemes/animethemes-server#650]
Using the following request (copied from the api page) : (url=https://api.animethemes.moe/anime?filter[year-gt]=2000) the api returns a "Filter must be an array" error.
Same request has been working correctly till (at least) March 13.

**Comment by Kyrch** [comment]
Should be fixed now #652

**Comment by ferrazza11** [comment]
It does, tnx for the fast fix
