### ISSUE TITLE
Support random ordering of API resources

### ISSUE THREAD

**Issue by buzzbyte** [AnimeThemes/animethemes-server#77]
When I was testing the API, I found that the ability to filter by relations would be very useful for browsing and necessary for some use cases.
For example, this would allow a user to only search for videos that have `overlay: "None"` _and_ its theme is of `type: "OP"` and maybe they also want to avoid spoilers, so they filter the entries to only include `spoiler: false`.
Currently, this is not possible with the current filtering strategy as the resource endpoints lack the ability to filter by their relations.

As for the Random API endpoint, I've found it to be useful in a lot of cases while I was experimenting with the API, especially when using filters with it.
I began experimenting with an implementation of it, and I propose using `/random/{resource}` as the endpoint path, where `{resource}` is any of `anime`, `theme`, `artist`, `entry`, `series`, `song`, or `video`. The endpoint would respond with an array of randomly picked items from the resource of the length specified in the query (defaults to 1, maximum allowed could be 30).
`include`, `fields`, and `filter` parameters could also be applied to the query.

I'll draft a pull request with an implementation of both of these features.

**Comment by paranarimasu** [comment]
This issue has gone stale so I just want to refocus it.

As of 344ed0e62eed4af02c3042ded02efa79202b6671 we support deep filtering by way of constrained eager loading.

In the initial design discussion we had wanted to separate the random endpoints and resolve the resource type by name. I no longer believe this is the approach we should take.

Proposal:

* Support a new `random` flag in the query string for API requests. The [QueryParser](https://github.com/AnimeThemes/animethemes-server/blob/wiki/app/Http/Api/QueryParser.php) should tell us if the user has requested random ordering.
* In our [performQuery](https://github.com/AnimeThemes/animethemes-server/blob/wiki/app/Http/Resources/BaseCollection.php#L103) function, we should check for this flag. If set to true, ignore sorting and modify the query builder with `inRandomOrder`.

I'm guessing but am not sure that pagination doesn't play nicely with this function so perhaps we should use a `limit` here.

**Comment by paranarimasu** [comment]
https://github.com/laravel/framework/blob/93e104d96924019986b24350f5090409725f8792/src/Illuminate/Database/Query/Builder.php#L2033

Seeding is supported so if possible, let's try to preserve pagination to reduce complexity.

**Comment by paranarimasu** [comment]
To refine this a little bit further, I think we need to extract sorting to a separate set of classes similar to Conditions:

* IdSort: mutate "id" key to primary key name
* FieldSort: applies sort to direct field
* RelationFieldSort: applies subselect sort to relation field (I don't think a join is going to work in the transformation layer)
* RandomSort: applies random order sort

In the query string parsing context:

* If value is "id", make IdSort
* If value is "random", make RandomSort
* If value contains ".", make RelationFieldSort
* Else make "FieldSort"

Like the condition objects, sort objects shall have a function to modify the builder.

**Comment by paranarimasu** [comment]
Final item has been moved to #281 for a future effort. Closing.
